name: Continuous Integration Pipeline

on:
  push:
    branches: [ main, donath ]
  pull_request:
    branches: [ main, donath ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v2 

     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

     -  name: Set up QEMU
        uses: docker/setup-qemu-action@v3

     -  name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

     -  run: |
         cd DockerHandsOn/Exercice-Compose
         ls -l

    

    #  -  name: Build and push images to Docker Hub
    #     uses: docker/build-push-action@v4
    #     with:
    #       context: ./DockerHandsOn/Exercice-Compose
    #       push: true
    #       tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:${{ github.sha }}

     -  name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USERNAME }}
         key: ${{ secrets.KEY }}
         port: ${{ secrets.PORT }}
         fingerprint: "AAAAB3NzaC1yc2EAAAADAQABAAABAQCeOgyqHqMMAsaok9i0xfsFxIhHPQ24WJ+i8UxyVelFmuU8tHxLwwXj9kg7bVkKx6JcCrCTPhlV5qrwlMAY83Yiof6YhrUK8pNzdnQ+5xb6T/eLwjZFo6J8wxiWpwRHy6RWSLx4luZLS73eIXf9Cd9zZwELIsY1e9RZYNfFVpAxyj5J09eMzTs1q3FF/OQ1WSKfp6XHqOPsghLwA9wq7vVIZntioCAQDO7YFbuijJBL5gMMpQgeu1fuZbr5wZpTY3M9Mf0PN4LGOm/r7r4ZCvMp4d+9x7oT/Y8x3sH/BLnxqTbuSPQ6LV98Zifvb80C23d37R4NhE4qYdiQHsyWgZ+H"
         script: whoami
     
